# Коллекции данных

## 1. Диапазон чисел (range)

Конструирует специализированный массив равно отстоящих числовых элементов

### Вариант с шагом 1 по умолчанию

```
j = start:stop
```
или 
```
j = range(start, stop)
j = range(start; stop)
```

In [9]:
j = -5:5

-5:5

In [10]:
k = range(-5, stop=5)

-5:5

In [11]:
j == k

true

обращение по индексу

In [12]:
j[4]

-2

проверка наличия элемента в коллекции

In [13]:
2 ∈ j

true

### Вариант с заданным шагом
```
j = start:step:stop
```
или
```
j = range(start, stop; step)
```

In [14]:
j = -5:0.2:5

-5.0:0.2:5.0

In [15]:
k = range(-5, 5, step = 0.2)
k == j

true

### Вариант с заданным числом элементов

```
j = range(start; length)
j = range(start, stop, length)
j = range(start, stop; length)
j = range(start; stop, length)
j = range(start; length, step)
```

In [16]:
j = range(1, length=9, step=2)

1:2:17

### Часто используемые методы с `range`:

```
length(j) - вернуть число элементов 
collect(j) - конвертировать в массив
```

In [17]:
j = 3:0.3:6

3.0:0.3:6.0

In [18]:
length(j)

11

In [19]:
collect(j)

11-element Vector{Float64}:
 3.0
 3.3
 3.6
 3.9
 4.2
 4.5
 4.8
 5.1
 5.4
 5.7
 6.0

### Области применения
- циклы
- слайсы
- сетки (для графики)
- ...

In [20]:
for i in 1:5            # или for i=1:5 или for i ∈ 1:5
    println(i)
end

1
2
3
4
5


In [21]:
A = collect(1:10)       
A[3:5]

3-element Vector{Int64}:
 3
 4
 5

In [22]:
A

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

# 2. Массивы

Массивы - это упорядоченная коллекция элементов. 


## 2.1. Создание массивов

Все, что заключается в [...] - это массив

### Одномерный массив

In [23]:
A = [1, 2, 3]   # массив целых чисел

3-element Vector{Int64}:
 1
 2
 3

In [24]:
A = [2, 'W', 1//5, "Julia"]  # Элементы массива могут быть любого типа

4-element Vector{Any}:
  2
   'W': ASCII/Unicode U+0057 (category Lu: Letter, uppercase)
 1//5
   "Julia"

In [25]:
A = [ [1, 2, 3, 4, 5], [3//4, 4//5], ["Julia", "Romeo"] ] # в том числе массивами

3-element Vector{Vector}:
 [1, 2, 3, 4, 5]
 Rational{Int64}[3//4, 4//5]
 ["Julia", "Romeo"]

In [26]:
A = [sin, cos, tan]  # и функциями

3-element Vector{Function}:
 sin (generic function with 13 methods)
 cos (generic function with 13 methods)
 tan (generic function with 12 methods)

Чтобы создать массив элементов конкретного типа, его следует указать перед [ ]

In [27]:
A = Float64[1, 2, 3, 4//5, 4pi]  # массив вещественных чисел

5-element Vector{Float64}:
  1.0
  2.0
  3.0
  0.8
 12.566370614359172

In [28]:
A = String[]   # пустой массив строковых элементов

String[]

### Двухмерный массив
Если опустить запятые между элементами, будет создан двухмерный массив

In [29]:
A = [1 2 3 4 5 6]    # Двухмерный массив 1 х 6

1×6 Matrix{Int64}:
 1  2  3  4  5  6

In [30]:
A = [1 2 3; 4 5 6; 7 8 9]  # Двухмерный массив 2 х 3

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

### Многомерный массив


In [31]:
A = [1 2 3         # Трехмерный массив 2 х 3 х 2
     2 3 4;;;      # количество ";" в разделителе осей определяет размерность
     3 4 5
     5 6 7]

2×3×2 Array{Int64, 3}:
[:, :, 1] =
 1  2  3
 2  3  4

[:, :, 2] =
 3  4  5
 5  6  7

In [32]:
A = [1 2 3; 2 3 4;;; 3 4 5; 6 6 7]

2×3×2 Array{Int64, 3}:
[:, :, 1] =
 1  2  3
 2  3  4

[:, :, 2] =
 3  4  5
 6  6  7

### Использование генераторов для создания массивов


In [33]:
A = [x for x in 1:5]    # collect(1:5)

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [34]:
A = [abs2(sin(x)) for x = -2pi:pi/5:0]

11-element Vector{Float64}:
 5.99903913064743e-32
 0.34549150281252655
 0.9045084971874738
 0.9045084971874736
 0.34549150281252616
 1.4997597826618576e-32
 0.34549150281252644
 0.9045084971874738
 0.9045084971874736
 0.3454915028125263
 0.0

In [35]:
A = [x^2 for x in 2:8 if x!=5]

6-element Vector{Int64}:
  4
  9
 16
 36
 49
 64

### Создание массивов с заполнением


In [36]:
A = zeros(3)   # Создать одномерный массив из трех нулей 

3-element Vector{Float64}:
 0.0
 0.0
 0.0

In [37]:
A = ones(Int64, 3,3)   # Создать двухмерный массив 3x3 заполненный единицами

3×3 Matrix{Int64}:
 1  1  1
 1  1  1
 1  1  1

In [38]:
A = trues(3,2)  # Создать двухмерный массив 3x2, заполненный булевой истинной

3×2 BitMatrix:
 1  1
 1  1
 1  1

In [39]:
A = rand(3)   # одномерный массив, заполненный равномерно распределенными случайными числами от 0 до 1

3-element Vector{Float64}:
 0.931943379561659
 0.5893300349012093
 0.9969516320796115

In [40]:
A = randn(2,3) # двухмерный массив со случайными числами, распределенными по стандартному нормальному закону N(0,1)

2×3 Matrix{Float64}:
 -0.189669  -0.0627219  -0.179814
  1.46328   -0.484587   -0.261734

In [41]:
A = fill("bla", 2, 3)   # Создать массив 2 х 3, заполнив его "bla"

2×3 Matrix{String}:
 "bla"  "bla"  "bla"
 "bla"  "bla"  "bla"

In [43]:
fill!(A,"ахаха")        # заполнить массив новым значением (! указывает, что массив A будет изменен)

2×3 Matrix{String}:
 "ахаха"  "ахаха"  "ахаха"
 "ахаха"  "ахаха"  "ахаха"

In [44]:
using Random

A = rand(2,4)

2×4 Matrix{Float64}:
 0.350695  0.233176  0.793078  0.011214
 0.31084   0.646415  0.958026  0.962568

In [45]:
rand!(A)

2×4 Matrix{Float64}:
 0.513826  0.275497   0.179022  0.693325
 0.576827  0.0783048  0.626658  0.991907

### Создание массивов размножением


In [46]:
a = [0, 50, 100]     
A = repeat(a, 3)     # создать массив A из массива a, повторив его три раза вдоль первого измерения

9-element Vector{Int64}:
   0
  50
 100
   0
  50
 100
   0
  50
 100

In [47]:
a = [0 50 
    50 100]
A = repeat(a, 2, 3)   # создать массив A из a, повторив его 2 раза вдоль 1го измерения и 3 раза вдоль 2й измерения

4×6 Matrix{Int64}:
  0   50   0   50   0   50
 50  100  50  100  50  100
  0   50   0   50   0   50
 50  100  50  100  50  100

### Конструктор массивов

Часто эффективно предварительно выделить память под массив, а затем заполнять его по мере вычислений 

`Array  { T, dim } (undef, s1, s2, ... ) 
  |      |   |              |   |         
  |      |   |              |   ∟—  Число элементов вдоль второго измерения
  |      |   |              ∟—————  Число элементов вдоль первого измерения
  |      |   ∟—————————————  Размерность массива 
  |      ∟—————————————————  Тип элементов массива 
  ∟————————————————————————  Ключевое слово`

In [48]:
A = Array{Int64,3}(undef,2,2,2)    # Создать неинициализированный 2 x 2 x 2 массив целых

2×2×2 Array{Int64, 3}:
[:, :, 1] =
 4503599628423168     4521192081854464
 4521260801331216  1157425104503705600

[:, :, 2] =
 1152939096792891408  1157442696420266000
      17661175005200                    0

In [49]:
A = Array{String,2}(undef,2,3)  # Создать неинициализорованный 2х3 массив строк

2×3 Matrix{String}:
 #undef  #undef  #undef
 #undef  #undef  #undef

In [50]:
A = Array{Array{String,2},2}(undef,2,2)  # Создать 2х2 массив 2-мерных массивов строк

2×2 Matrix{Matrix{String}}:
 #undef  #undef
 #undef  #undef

In [51]:
M = Matrix{Float64}(undef,2,2)   # Создать неиницилизированную матрицу чисел 2 x 2

2×2 Matrix{Float64}:
 6.95245e-310  6.95245e-310
 6.95245e-310  6.95245e-310

In [52]:
M = Vector{Float64}(undef,5)   # Создать неиницилизированный вектор 5 чисел

5-element Vector{Float64}:
 6.95245306130697e-310
 6.95245306130697e-310
 6.95245306130697e-310
 6.95245306130697e-310
 2.5e-323

Создать пустой массив

In [53]:
A = Float64[]     # Создать пустой массив для чисел

Float64[]

In [54]:
A = String[]      # Создать пустой массив для строк

String[]

In [55]:
A = []              # Создать пустой массив, для элементов любого типа

Any[]

## 2.2. Доступ к элементам массива

В Julia нумерация начинается с 1, а не с 0 как в С и Python

In [56]:
A = [11, 22, 33, 44, 55, 66, 77, 88];

In [57]:
A[3] # элемент по индексу 3

33

In [58]:
A[end]  # последний элемент

88

In [59]:
A[begin] # первый элемент

11

In [60]:
A[end-1] # предпоследний элемент

77

In [61]:
A[[1,4,7]]  # выборка из 1-, 4- и 7-го элементов 

3-element Vector{Int64}:
 11
 44
 77

In [62]:
A = [10 20 30 
     40 50 60]

2×3 Matrix{Int64}:
 10  20  30
 40  50  60

In [63]:
A[4]  # 4-й по порядку элемент (в Julia массивы храняться по столбцам)

50

In [64]:
A[2,3]  # элемент второй строки, третьего столбца

60

Используйте `:` для доступа ко всей строке/столбцу/матрице

In [65]:
A[:,2]  # все элементы второго столбца

2-element Vector{Int64}:
 20
 50

In [66]:
A[1,:] # все элементы первой строки

3-element Vector{Int64}:
 10
 20
 30

In [67]:
A[:]   # все элементы матрицы (удобно для разворячивания в вектор, аналог vec())

6-element Vector{Int64}:
 10
 40
 20
 50
 30
 60

In [68]:
A[1, 2:3] # 2- и 3-й элементы первой строки

2-element Vector{Int64}:
 20
 30

Логическая индексация

In [69]:
A = collect(1:5)
A[[true, false, true, false, true]]   # вернуть элементы с true в позиции индекса

3-element Vector{Int64}:
 1
 3
 5

In [70]:
A[A.>3]        # вернуть элементы, удовлетворяющие условию

2-element Vector{Int64}:
 4
 5

In [71]:
A.>3

5-element BitVector:
 0
 0
 0
 1
 1

### Эффективный доступ к подмассивам: view()

Операция `b = A[4:8]` создает в памяти новый массив. Чтобы работать с частью массива без выделения памяти, используйте `view()` или макрос `@view`

In [72]:
A = [1 2 3 4 5 6 7]
b = view(A, 3:4)     # подмассив из 3 и 4 элемента

2-element view(::Vector{Int64}, 3:4) with eltype Int64:
 3
 4

In [73]:
fill!(b, 999)        # изменение значений подмассива ведет к изменению в исходном массиве

2-element view(::Vector{Int64}, 3:4) with eltype Int64:
 999
 999

In [74]:
A

1×7 Matrix{Int64}:
 1  2  999  999  5  6  7

In [75]:
A = [1 2 3 4 5 6 7]
b = @view A[end-2:end]    # макрос удобно использовать, когда используются begin и end

fill!(b,111)
A

1×7 Matrix{Int64}:
 1  2  3  4  111  111  111

Демонстрационный пример

In [77]:
function foo(A)
     sum(abs2, A)   # вычислить Σ(aᵢⱼ)²
end
        
A = randn(1000,1000)

@time s1 = foo(A[:, 200:900])      # при передаче создается новая матрица
@time s2 = foo(view(A,:,200:900))  # здесь передается подматрица

  0.008194 seconds (776 allocations: 5.394 MiB, 54.14% compilation time)
  0.005115 seconds (771 allocations: 46.770 KiB, 92.68% compilation time)


701250.1487736456

In [78]:
s1 == s2

true

## 2.3. Модификация массивов
### Добавление элементов

In [79]:
# Чтобы добавить новый элемент к массиву используйте push! или append!
A = [1,2,3]

push!(A,10,6)            # добавить два элемента 10 и 6
append!(A,[20,30])       # присоединяет массив

A

7-element Vector{Int64}:
  1
  2
  3
 10
  6
 20
 30

In [80]:
# Чтобы добавить элемент в начало списка, используйте pushfirst! или prepend!
A = [1,2,3]

pushfirst!(A,-5)            # добавить -5 в начало
prepend!(A,[-20,-30])       # присоединить в начало массив

A

6-element Vector{Int64}:
 -20
 -30
  -5
   1
   2
   3

In [81]:
# Чтобы добавить в конкретную позицию используйте insert!
A = [1,2,3,4]

insert!(A, 3, 100)           # вставить 100 в 3-ю позицию

5-element Vector{Int64}:
   1
   2
 100
   3
   4

### Удаление элементов

In [82]:
# Чтобы удалить элемент, используйте pop! или popfirst!
A = [1,2,3,4,5]

pop!(A)              # удалить последний элемент
popfirst!(A)         # удалить первый элемент

A

3-element Vector{Int64}:
 2
 3
 4

In [83]:
# Чтобы удалить в конкретной позиции, используйте deleteat!
A = [1,2,3,4,5]

deleteat!(A, 3)       # удалить 3й элемент
print(A)

deleteat!(A, [2,4])   # удалить 2й и 4й элемент

[1, 2, 4, 5]

2-element Vector{Int64}:
 1
 4

In [84]:
# Чтобы удалить все элементы, используйте empty!
A = [1,2,3,4,5]
empty!(A)

Int64[]

### Объединение (конкатенация) массивов

In [85]:
# Сочленить два массива по вертикали
A =  [1 2 3 
      4 5 6]

B = -[1 2 3 
      4 5 6]

C = [A; B]                 # или C = vcat(A,B) или С = cat(A,B, dims=1)

4×3 Matrix{Int64}:
  1   2   3
  4   5   6
 -1  -2  -3
 -4  -5  -6

In [86]:
# Сочленить два массива по горизонтали
C = [A B]                # или C = hcat(A,B) или C = cat(A,B,dims=2)

2×6 Matrix{Int64}:
 1  2  3  -1  -2  -3
 4  5  6  -4  -5  -6

### Пермутации массива

In [87]:
# Преобразовать вектор в матрицу
A = [1,2,3,4]                   # одномерный массив 4х1
reshape(A,2,2)                  # двухмерный 2x2 массив

2×2 Matrix{Int64}:
 1  3
 2  4

In [88]:
# Можно менять измерения двухмерного матрицы
A = [1  2  3
     4  5  6 
     7  8  9 
     10 11 12]     # массив 4х3

reshape(A, 6, 2)   # массив 6х2

6×2 Matrix{Int64}:
  1   8
  4  11
  7   3
 10   6
  2   9
  5  12

In [89]:
# Преобразовать вектор в 4-мерный массив
A = reshape(Vector(1:16), (2, 2, 2, 2))

2×2×2×2 Array{Int64, 4}:
[:, :, 1, 1] =
 1  3
 2  4

[:, :, 2, 1] =
 5  7
 6  8

[:, :, 1, 2] =
  9  11
 10  12

[:, :, 2, 2] =
 13  15
 14  16

In [90]:
# Удалить "пустую" размерность
A = reshape(Vector(1:4), (2, 2, 1, 1))
print(A)

dropdims(A, dims=4)    # удалить 4-ю размерность

[1 3; 2 4;;;;]

2×2×1 Array{Int64, 3}:
[:, :, 1] =
 1  3
 2  4

In [91]:
# "Вращать" массив
A = [1,2,3,4,5]

circshift(A, 1)      # сместить элементы на одну позицию

5-element Vector{Int64}:
 5
 1
 2
 3
 4

In [92]:
A = [1  5   9  13
     2  6  10  14
     3  7  11  15
     4  8  12  16]

circshift(A, (0,2))   # сместить столбцы на две позиции

4×4 Matrix{Int64}:
  9  13  1  5
 10  14  2  6
 11  15  3  7
 12  16  4  8

In [93]:
# Поменять местами оси
A = [1  5   9  13
     2  6  10  14
     3  7  11  15
     4  8  12  16]

permutedims(A)                

4×4 Matrix{Int64}:
  1   2   3   4
  5   6   7   8
  9  10  11  12
 13  14  15  16

In [94]:
# Tранспонировать 
transpose(A)

4×4 transpose(::Matrix{Int64}) with eltype Int64:
  1   2   3   4
  5   6   7   8
  9  10  11  12
 13  14  15  16

In [95]:
# Aᵀ
Matrix(A')

4×4 Matrix{Int64}:
  1   2   3   4
  5   6   7   8
  9  10  11  12
 13  14  15  16

### Создание копии массива

`B = A` не создает копии массива A, но лишь новый указатель на него

In [96]:
# Для создания копии массива используйте copy()
A = [1 2 3    
     4 5 6]

B = copy(A)     # Полноценная копия


2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [97]:
A === B

false

In [98]:
B=A

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [99]:
# Для создания копии сложной структуры данных
# например, массива массивов используйте deepcopy()
A = [ [1 2; 3  4], [3 4; 5 6] ]
B = deepcopy(A)

2-element Vector{Matrix{Int64}}:
 [1 2; 3 4]
 [3 4; 5 6]

## 2.4. Характеристики массива

```
ndims(A)      Размерность массива
size(A)       Количество осей (строк и столбцов) массива
length(A)     Общее число элементов массива 
eltype(A)     Тип элементов массива
```

In [100]:
A = [1.0 2 3; 3 6 4]

2×3 Matrix{Float64}:
 1.0  2.0  3.0
 3.0  6.0  4.0

In [101]:
eltype(A)

Float64

## 2.5. Разреженные массивы 

Разреженные матрицы используются в задачах электроэнергетики и других областях, связанных с сетевыми объектами

Примеры:
- матрица инциденций графа сети
- матрица проводивостей электрической сети
- дифференциальное уравнение в частных производных

Для представления данных с помощью разреженных матриц см. стандартную библиотеку [SparseArrays](https://docs.julialang.org/en/v1/stdlib/SparseArrays/)

Линейная алгебра для разреженных массивов представлена стандартной библиотекой [SuiteSparse](https://docs.julialang.org/en/v1/stdlib/SuiteSparse/) и другими пакетами экосистемы Julia

In [102]:
using SparseArrays

B = [1 0 0 0; 
     0 2 3 0; 
     0 0 5 0]

3×4 Matrix{Int64}:
 1  0  0  0
 0  2  3  0
 0  0  5  0

In [103]:
A = sparse(B)      # конвертировать в разреженную матрицу

3×4 SparseMatrixCSC{Int64, Int64} with 4 stored entries:
 1  ⋅  ⋅  ⋅
 ⋅  2  3  ⋅
 ⋅  ⋅  5  ⋅

In [104]:
A = sprand(1000,1000,0.001) # создать случайную разреженную матрицу с плотностью 0.001, 

1000×1000 SparseMatrixCSC{Float64, Int64} with 1001 stored entries:
⠀⠀⠈⠂⠌⠈⠢⢈⠄⠀⠄⠀⠐⡀⠶⠀⢀⡄⠰⠀⣄⢀⣀⠆⠀⠠⠠⡀⠀⠓⠀⠆⢀⠀⠡⠠⠄⠠⠀⠀
⠀⠀⢥⠠⢀⠂⢈⢀⠠⠐⠐⠠⠢⠂⣀⠀⠐⢈⠡⡀⡄⠈⠐⠕⠀⠀⢀⡀⠀⡆⠂⢒⠠⠁⠀⠨⠅⠰⡀⠐
⠨⡐⢐⣀⡆⠁⠁⠀⠂⢌⡀⠀⠢⠀⠀⠡⠀⣀⠠⡀⠅⠂⠐⠠⢀⠀⠀⢊⠀⠈⠅⠆⡔⠀⠄⠀⠲⢀⠰⠀
⠀⡀⠈⢁⠀⡃⢐⡀⠀⠠⠀⠀⠈⡄⠁⠀⠀⠂⠢⠀⢁⠀⣀⠈⠂⠅⢠⠀⠀⠂⡸⡐⠄⠂⠀⠉⠂⣀⠀⠂
⠀⠄⠂⠀⢀⠀⡆⠀⠠⢀⠀⠁⡀⠈⠀⠀⢐⠀⡐⠀⠀⠀⠀⠀⠈⢐⠂⠀⢢⠠⠀⠆⠉⠁⡈⠌⢀⠒⠠⠈
⠡⠐⠇⠄⠀⠄⠀⠨⠈⠄⠀⠠⠀⢂⠁⢀⠃⠠⠡⠄⢈⠂⠀⠄⡁⠀⡲⠑⠀⠨⢀⠀⠌⣀⠀⡃⢂⢁⠘⠀
⠏⠁⠠⠐⠀⢀⡀⡖⠀⠀⢂⠜⠀⢂⠁⢀⠐⠀⢃⢀⠄⠠⢈⠀⢐⠀⠂⠅⠊⢀⠀⡀⡀⡐⢰⠁⡪⠀⠀⡀
⠑⠄⢡⠐⠐⢠⠀⠀⢀⠀⠀⠄⡠⡀⠀⠀⠁⠎⢀⠀⠠⢀⢀⠁⠀⡂⠢⣀⠀⠄⠨⠄⠀⡂⠐⠁⠂⠀⣀⠂
⠃⠐⢤⠐⠀⠉⠀⠐⢂⡀⠠⠂⠂⠑⠔⠀⠀⠑⠐⡠⠊⡐⢈⢀⠂⠨⠠⠀⠀⡠⣀⡄⠂⠠⠀⡀⢂⠈⠀⠠
⢀⡖⠄⣂⠒⠄⠁⢈⢐⡠⢀⢀⠂⠠⢀⠀⢈⠀⠆⠂⡀⠀⠀⠁⠀⡔⠄⠀⠐⠀⠁⢄⠊⢆⠂⠰⠀⠑⡀⠠
⠈⠀⠀⠄⡂⠀⣀⡠⠀⠊⠄⠂⠂⠠⡀⠠⠀⠀⠄⠃⠀⢨⡀⠄⠀⣁⠀⠐⢰⠀⣀⠀⠈⠀⠨⡂⡀⠐⠀⠀
⠀⠨⠀⠈⢡⠠⠀⠠⠁⠀⠐⠀⠠⠀⡂⠫⠄⠠⠀⠂⠈⠁⡀⠀⠀⢄⠉⠄⠠⠨⠀⢀⠀⠀⡀⠠⢢⠆⡠⢀
⡀⠀⠅⠄⠨⠀⠀⢂⠂⠀⢰⠀⢡⠀⢀⠀⠁⠈⢀⠔⠀⠐⡀⠀⢀⠐⠊⠄⠒⠂⢂⠠⠐⠀⠔⢂⠐⠐⠄⠁
⠀⢔⠠⠀⡈⠐⠂⡐⠀⢂⢀⠤⡈⠀⠠⠀⠈⠂⠀⠀⠐⠙⢂⢀⠱⡐⠁⠀⠄⠐⢄⠠⡑⢀⠈⡀⠄⠀⠂⠄
⠤⠐⡰⢁⡢⠂⠈⠐⠆⠈⠀⣁⠃⠀⢀⠀⢠⠀⠀⠉⡀⠠⠣⠀⢤⢐⠄⡂⠀⡀⠀⠢⠀⡀⠠⣐⡒⠄⠤⠀
⠀⣂⠂⡀⡑⠀⠀⠠⢀⢈⡀⠨⠐⡀⠁⠁⠃⠀⠁⠲⢤⠀⠐⠂⠄⠀⠁⠠⠀⣀⠂⠂⠩⠀⡀⢀⠀⠀⠐⠐
⠁⡈⠀⠀⡂⠀⡈⠠⠈⠠⠣⠀⢂⠠⠉⢂⠐⠀⡀⢀⠉⢡⢠⡰⠠⠀⡀⢈⠀⠀⠘⠀⠈⡂⠨⠊⡉⢄⡢⠀
⢀⠠⡀⠰⠠⠀⠀⠠⠀⢐⠈⠠⠁⠤⠄⡡⢀⠀⢀⠁⠀⠀⠀⡩⠈⠁⠀⠀⠐⡠⣂⢄⠀⠀⡀⠡⡬⠀⠀⠂
⠠⠁⠄⠠⠐⠰⠶⠡⠂⡠⠓⠁⠑⢈⠣⠐⡀⠈⠀⢈⠀⠅⠄⠀⠀⠁⠘⡐⠀⢄⠀⠰⠄⠀⠀⠀⠁⠈⠀⡊
⠄⠠⠀⢀⠀⠐⠀⡠⠀⠩⡀⠁⠀⠉⡀⢀⠈⠀⠈⠀⠀⠐⠤⠨⠌⡀⠐⠁⢁⠁⢄⠀⠂⠐⠂⠈⠂⠠⠡⠀

В разреженном формате матрица хранит N ненулевых элементов и занимает ≈ 3xNx8 байт

In [105]:
println("Элементов: ", nnz(A))
println("Байтов:    ", Base.summarysize(A))

Элементов: 1001
Байтов:    24184


В плотном формате матрица содержит 1_000_000 элементов и занимает ≈ size х size х 8 байт

In [106]:
B = Matrix(A)          # конвертируем в плотный формат

println("Элементов: ", prod(size(B)))
println("Байтов:    ", Base.summarysize(B))

Элементов: 1000000
Байтов:    8000040


Время на выполнение операций зависит от числа элементов

In [108]:
@time A*A; # sparse
@time B*B; # full

  0.000063 seconds (7 allocations: 42.078 KiB)
  0.027932 seconds (2 allocations: 7.629 MiB)


## 3. Кортеж

Кортеж - упорядоченная коллекция элементов, отличающаяся от массива тем, что она неизменяемая. К ней нельзя добавить новые элементы или удалить имеющиеся.

### Обычные кортежи (tuple)

In [109]:
# Создать кортеж
A = (1, 2.5, "s", [1,2,3], 5//7, pi)

(1, 2.5, "s", [1, 2, 3], 5//7, π)

In [110]:
# Кортеж из одного элемента (запятая обязательна)
a = (50,)

(50,)

In [111]:
# Доступ к элементам
A[3:5]

("s", [1, 2, 3], 5//7)

In [112]:
# Преобразовать в массив
B = collect(A)

6-element Vector{Any}:
  1
  2.5
   "s"
   [1, 2, 3]
 5//7
  π = 3.1415926535897...

In [113]:
# Изменить нельзя
A[4]=6

LoadError: MethodError: no method matching setindex!(::Tuple{Int64, Float64, String, Vector{Int64}, Rational{Int64}, Irrational{:π}}, ::Int64, ::Int64)

In [114]:
# Число элементов кортежа
length(A)

6

In [115]:
foo(x)=x^2

# Создать кортеж используя функцию ntuple (см. ?ntuple)
B=ntuple(foo, 4)

(1, 4, 9, 16)

In [116]:
# Проверить наличие элемента в кортеже
9 in B

true

In [117]:
# Распаковать кортеж (присвоить значения элементов переменным)
a,b,c,d = B
c

9

In [118]:
# преобразовать набор элементов в кортеж
a=[1,2,3,4]

tuple(a...)

(1, 2, 3, 4)

In [119]:
# или
Tuple(a)

(1, 2, 3, 4)

### Именованные кортежи (namedtuple)

In [120]:
# Создать именованный кортеж
z = (a=1, b=2)

(a = 1, b = 2)

In [121]:
# Обращение по индексу
z[1]

1

In [122]:
# по имени
z[:a]

1

In [123]:
# или
z.a

1

In [124]:
# Имена элементов
keys(z)

(:a, :b)

In [125]:
# Значения элементов
values(z)

(1, 2)

In [126]:
# При конвертировании в вектор имена теряются
collect(z)

2-element Vector{Int64}:
 1
 2

In [127]:
# Конвертирование в вектор пар ключ=>значение
collect(pairs(z))

2-element Vector{Pair{Symbol, Int64}}:
 :a => 1
 :b => 2

# 4. Множество

Множество - коллекция уникальных элементов

In [128]:
# Создать множество целых чисел, A = { 1, 4, 5, 7, 9} 
A = Set([1,4,5,7,9])

Set{Int64} with 5 elements:
  5
  4
  7
  9
  1

In [129]:
# Проверить принадлежность, 4 ∈ A ?
4 in A

true

In [130]:
# Создать пустое множество, C = Ø
C = Set{String}()

Set{String}()

In [131]:
# Добавление элементов "g" и "ty" в C
push!(C,"g","ty")

Set{String} with 2 elements:
  "g"
  "ty"

In [132]:
# Удаление элемента, C\{1}
delete!(C,"g")

Set{String} with 1 element:
  "ty"

In [133]:
# Объединение множеств, A ∪ B
A = Set([1,2,3,8,9])
B = Set([3,5,6,8])

С = union(A,B)

Set{Int64} with 7 elements:
  5
  6
  2
  9
  8
  3
  1

In [134]:
# Пересечение множеств, A ∩ B
intersect(A,B)

Set{Int64} with 2 elements:
  8
  3

In [135]:
# Разность множеств, A \ B
setdiff(A,B)

Set{Int64} with 3 elements:
  2
  9
  1

In [136]:
# Симметрическая разность, A Δ B 
Z=symdiff(A,B)

Set{Int64} with 5 elements:
  5
  6
  2
  9
  1

In [137]:
# Проверка включения, A ⊆ B
issubset(A, B)

false

In [138]:
# Преобразовать в массив
B = collect(A)

5-element Vector{Int64}:
 2
 9
 8
 3
 1

In [139]:
# Создать упорядоченное множество (только для целых)
A = BitSet([10,2,3])

BitSet with 3 elements:
  2
  3
  10

## 5. Словарь

Словарь - ассоциативная коллекция для хранения данных, доступных по ключу

Широко используются в Julia для организации сложных структур данных

 ### 5.1. Создание Словаря

In [140]:
# Словарь с двумя парами ключ->значение
Coord = Dict("Широта" => 61, "Долгота" => 50) 

Dict{String, Int64} with 2 entries:
  "Долгота" => 50
  "Широта"  => 61

In [141]:
# Ключами и значениями могут быть строки, числа, массивы, словари и т.п.
Inst = Dict("Наименование"  => "ИСЭиЭПС", 
            "Численность"   => 81,
            "Расположение"  => Coord, 
            "Подразделения" => ["Отдел региональных исследований" 
                                "Отдел социально-экономических проблем"
                                "Отдел энергетики"
                                "Лаборатория проблем транспорта"],
            [1.8, 3//7]     => 244267    
  ) 

Dict{Any, Any} with 5 entries:
  [1.8, 0.428571] => 244267
  "Наименование"  => "ИСЭиЭПС"
  "Расположение"  => Dict("Долгота"=>50, "Широта"=>61)
  "Подразделения" => ["Отдел региональных исследований", "Отдел социально-эконо…
  "Численность"   => 81

In [142]:
# При создании однородных словарей можно указать типы ключей и значений явно
point = Dict{String, Float64}("x" => 9.76, "y" => -8.54)

Dict{String, Float64} with 2 entries:
  "x" => 9.76
  "y" => -8.54

In [143]:
# Создать пустой словарь
A = Dict()

Dict{Any, Any}()

In [144]:
# Использование генераторов
A = Dict(x => x^2 for x=1:10)

Dict{Int64, Int64} with 10 entries:
  5  => 25
  4  => 16
  6  => 36
  7  => 49
  2  => 4
  10 => 100
  9  => 81
  8  => 64
  3  => 9
  1  => 1

### 5.2. Доступ к данным словаря 
#### по ключу

In [145]:
Inst["Расположение"]

Dict{String, Int64} with 2 entries:
  "Долгота" => 50
  "Широта"  => 61

In [146]:
Inst["Расположение"]["Долгота"]

50

In [147]:
Inst["Тел"]    # Упс... такого ключа нет

LoadError: KeyError: key "Тел" not found

In [148]:
# Используйте haskey для проверки наличия ключа 
haskey(Inst, "Тел")

false

In [149]:
# Используйте in для проверки вхождения пары ключ-значение в словарь
in("Численность" => 81, Inst)  

true

In [150]:
# или так 
Pair("Численность", 81) in Inst

true

In [151]:
Pair("Численность", 81)

"Численность" => 81

#### с помощью функции `get`

In [152]:
# для безопасного доступа используйте функцию get, возвращающую в случае отсутствия ключа назначенное значение
get(Inst, "Расположение", "Засекречено")

Dict{String, Int64} with 2 entries:
  "Долгота" => 50
  "Широта"  => 61

In [153]:
get!(Inst, "Тел", "Засекречено") # ! при отсутствии добавляет в словарь
Inst

Dict{Any, Any} with 6 entries:
  [1.8, 0.428571] => 244267
  "Наименование"  => "ИСЭиЭПС"
  "Расположение"  => Dict("Долгота"=>50, "Широта"=>61)
  "Тел"           => "Засекречено"
  "Подразделения" => ["Отдел региональных исследований", "Отдел социально-эконо…
  "Численность"   => 81

#### при итерировании


In [154]:
for pair in point
    println("Значение $(pair[1]) равно $(pair[2])")
end

Значение x равно 9.76
Значение y равно -8.54


In [155]:
for k in keys(point)
    println("Значение $k равно $(point[k])")
end

Значение x равно 9.76
Значение y равно -8.54


In [156]:
for (k,v) in point
    println("Значение $k равно $v")
end

Значение x равно 9.76
Значение y равно -8.54


### 2.3. Добавление/удаление пары ключ-значение, объединение

In [157]:
# Добавление третьей координаты z
point["z"]=3.3
point

Dict{String, Float64} with 3 entries:
  "x" => 9.76
  "z" => 3.3
  "y" => -8.54

In [158]:
# или с помощью функции get! 
get!(point, "vol", 2.0)
point

Dict{String, Float64} with 4 entries:
  "vol" => 2.0
  "x"   => 9.76
  "z"   => 3.3
  "y"   => -8.54

In [159]:
# Удаление 
delete!(point, "vol")
point

Dict{String, Float64} with 3 entries:
  "x" => 9.76
  "z" => 3.3
  "y" => -8.54

In [160]:
# Объединить два словаря
d1 = Dict("a"=>1, "b"=>2)
d2 = Dict("c"=>3, "d"=>4)

d = merge(d1,d2) 

Dict{String, Int64} with 4 entries:
  "c" => 3
  "b" => 2
  "a" => 1
  "d" => 4

## 6. Пример

Граф, или неориентированный граф $G$ — это упорядоченная пара $G := (V, E)$, где $V$ — это непустое множество вершин или узлов, а $E$ — множество пар вершин, называемых рёбрами. 

Рассмотрим граф с заданными множеством вершин _vertices_ и множеством ребер _edges_

<img src="graph.png" />

In [161]:
# Создадим граф
vertices = Set([1,2,3,4,5])             # множество вершин графа
edges = Set([(1,2),(2,3),(3,1),(1,4)])  # множество ребер графа

G = Dict("V"=>vertices, "E"=>edges)     # граф G

Dict{String, Set} with 2 entries:
  "V" => Set([5, 4, 2, 3, 1])
  "E" => Set([(1, 2), (3, 1), (1, 4), (2, 3)])

In [162]:
# Список ребер
for e in G["E"]
    println(e)
end

(1, 2)
(3, 1)
(1, 4)
(2, 3)


In [163]:
# Добавим новое ребро
push!(G["E"], (2, 4))

for e in G["E"] 
    println(e) 
end

(2, 4)
(1, 2)
(3, 1)
(1, 4)
(2, 3)


In [164]:
# Вычислим валентность (степень) узлов
deg = zeros(Int64, length(G["V"]))  # нулевой вектор

for e in G["E"]
    deg[e[1]] += 1
    deg[e[2]] += 1
end

deg

5-element Vector{Int64}:
 3
 3
 2
 2
 0

In [165]:
# Построим матрицу смежности
A = zeros(Int64, length(G["V"]), length(G["V"])) # нулевая матрица

for (i,j) in G["E"]
    A[i,j] = 1
    A[j,i] = 1
end
A


5×5 Matrix{Int64}:
 0  1  1  1  0
 1  0  1  1  0
 1  1  0  0  0
 1  1  0  0  0
 0  0  0  0  0

In [166]:
# Построим разреженную матрицу смежности
A = spzeros(Int64, length(G["V"]), length(G["V"])) # нулевая матрица

for (i,j) in G["E"]
    A[i,j] = 1
    A[j,i] = 1
end
A

5×5 SparseMatrixCSC{Int64, Int64} with 10 stored entries:
 ⋅  1  1  1  ⋅
 1  ⋅  1  1  ⋅
 1  1  ⋅  ⋅  ⋅
 1  1  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅

In [167]:
# Представление графа в виде структуры
G

Dict{String, Set} with 2 entries:
  "V" => Set([5, 4, 2, 3, 1])
  "E" => Set([(2, 4), (1, 2), (3, 1), (1, 4), (2, 3)])

In [168]:
# Представление графа в виде матрицы смежности
A

5×5 SparseMatrixCSC{Int64, Int64} with 10 stored entries:
 ⋅  1  1  1  ⋅
 1  ⋅  1  1  ⋅
 1  1  ⋅  ⋅  ⋅
 1  1  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅